name: DevOpsLab

# Eventos que irão disparar esse workflow
on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:

  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      
      - name: Install Requirements
        run: pip install -r requirements.txt

      - name: Run Tests
        run: python -m unittest -v test

  deploy-to-heroku:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        # Busca todo o historico de commits para garantir que nao ocorram problemas de merge
        with:
          fetch-depth: 0

      - name: Heroku Login
        run: |
            cat > ~/.netrc <<EOF
              machine api.heroku.com
                login $HEROKU_EMAIL
                password $HEROKU_API_KEY
              machine git.heroku.com
                login $HEROKU_EMAIL
                password $HEROKU_API_KEY
            EOF
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
        
      # Adicionando o repositorio remoto do heroku para poder enviar o codigo da aplicacao
      - name: Add Heroku Remote
        run: |
          heroku git:remote --app $HEROKU_APP_NAME
        env:
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
        
      # Deploy do codigo para o heroku
      - name: Deploy to Heroku
        run: |
          git push heroku HEAD:main --force