name: DevOpsLab

# Eventos que irão disparar esse workflow
on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:

  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      
      - name: Install Requirements
        run: pip install -r requirements.txt

      - name: Run Tests
        run: python -m unittest -v test